/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logarytm;

import static java.lang.Math.abs;
import static java.lang.Math.pow;

/**
 *
 * @author Konrad
 */
public class LogarytmJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LogarytmJFrame
     */
    double basedb;
    double exponentdb;
    double resultdb;
    String basest;
    String exponentst;
    String resultst;
    public LogarytmJFrame() {
        initComponents();
        errorLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        exponent = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        base = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        result = new javax.swing.JTextField();
        calcButtons = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Policz swój logarytm");

        exponent.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        exponent.setText("8");
        exponent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exponentActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("log");

        base.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        base.setText("2");
        base.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("=");

        result.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });

        calcButtons.setText("Oblicz!");
        calcButtons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcButtonsMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Wstaw dane w rubryki i zostaw jedną pustą");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("lub wstaw x");

        errorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorLabel.setText("Błąd:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exponent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(errorLabel)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(calcButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(exponent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(errorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calcButtons)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(3, 3, 3)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exponentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exponentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exponentActionPerformed

    private void baseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baseActionPerformed

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultActionPerformed

    private void calcButtonsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcButtonsMouseClicked
        errorLabel.setVisible(false);
        switch(checkfields())
        {
            //podstawa pusta
            case 1:
                convertexponent();
                convertresult();
                calcbase();
                break;
            //wykładnik
            case 2:
                convertbase();
                convertresult();
                calcexponent();
                break;
            //wynik logarytmu pusty
            case 3:
                convertbase();
                convertexponent(); 
                calcresult();
                break;
            default: 
                errorLabel.setText("Błąd: Zbyt mało lub zbyt dużo danych!");
                errorLabel.setVisible(true);
                break;
        }
    }//GEN-LAST:event_calcButtonsMouseClicked
    private int checkfields()
    {
        basest = base.getText();
        exponentst = exponent.getText();
        resultst = result.getText();
        int blankcount=0;
        //sprawdź puste
        if(basest.equals(""))
        {
            blankcount++;
        }
        if(exponentst.equals(""))
        {
            blankcount++;
        }
        if(resultst.equals(""))
        {
            blankcount++;
        }
        if(blankcount > 1)
        {
            return 9;
        }
        if(basest.equals("") || basest.equals("x") || basest.equals("X"))
        {
            return 1;
        }
        else if(exponentst.equals("") || exponentst.equals("x") || exponentst.equals("X"))
        {
            return 2;
        }
        else if(resultst.equals("") || resultst.equals("x") || resultst.equals("X"))
        {
            return 3;
        }
        return 0;
    }
    private double convertbase()
    {
        try
        {
            basedb = Double.parseDouble(basest);
            
        }
        catch(NumberFormatException e)
        {
            errorLabel.setText("Błąd: złe dane!");
            errorLabel.setVisible(true);
            return 1;
        }
        if(basedb<=0)
        {
            errorLabel.setText("Błąd: złe dane!");
            errorLabel.setVisible(true);
            return 1;
        }
        return basedb;
    }
    private double convertexponent()
    {
        try
        {
            exponentdb =  Double.parseDouble(exponentst);
            
        }
        catch(NumberFormatException e)
        {
            errorLabel.setText("Błąd: złe dane!");
            errorLabel.setVisible(true);
            return 0;
        }
        if(exponentdb<=0)
        {
            errorLabel.setText("Błąd: złe dane!");
            errorLabel.setVisible(true);
            return 1;
        }
        return exponentdb;
    }
    private double convertresult()
    {
        try
        {
            resultdb = Double.parseDouble(resultst);
           
        }
        catch(NumberFormatException e)
        {
            errorLabel.setText("Błąd: złe dane!");
            errorLabel.setVisible(true);
            return 0;
        }
         return resultdb;
    }
    private void calcbase()
    {
        Double div = 1/resultdb;
        Double var = pow(exponentdb,div);
        base.setText(var.toString());
    }
    private void calcexponent()
    {
        Double var = pow(basedb,resultdb);
        exponent.setText(var.toString());
    }
    private void calcresult()
    {
        Double myresult = new Double(1);
        Double step = new Double(1);
        if(exponentdb==1)
        {
           result.setText("0");
           return;
        }
        else if(exponentdb>basedb)
        {
            while(abs(pow(basedb,myresult)-exponentdb)>0.01)
            {
                if(pow(basedb,myresult)>exponentdb)
                {
                    myresult -= step;
                    step = step/2;
                }
                myresult += step;
                System.out.println(pow(basedb,myresult));
            }
        }
        else if(exponentdb<basedb)
        {
            myresult = 0.0;
            step = 0.1;
            while(abs(pow(basedb,myresult)-exponentdb)>0.01)
            {
                if(pow(basedb,myresult)>exponentdb)
                {
                    myresult -= step;
                    step = step/10;
                }
                myresult += step;
                System.out.println(pow(basedb,myresult));
            }
        }
        result.setText(myresult.toString());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogarytmJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogarytmJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogarytmJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogarytmJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogarytmJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField base;
    private javax.swing.JButton calcButtons;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextField exponent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField result;
    // End of variables declaration//GEN-END:variables
}
